services:
  app_escuela:
    build: backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "jdbc:mysql://reserva_escuela:3306/reserva-escuela?createDatabaseIfNotExist=true&serverTimezone=UTC"  # Corregido: elimina el guion antes de la variable
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      JWT_SECRET: 12345
      URL_FRONT: "http://localhost:5173"
      USERNAME_ENV_EMAIL: classkit23@gmail.com
      PASSWORD_ENV_EMAIL: cfnkpoefssinvlhe
    restart: always
    depends_on:
      reserva_escuela:
        condition: service_healthy

  reserva_escuela:
    image: mysql:9.1.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: reserva-escuela
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
